FROM node:24.15.0-slim

ARG PI_VERSION=latest
RUN npm install --global "@earendil-works/pi-coding-agent@${PI_VERSION}" \
    && npm cache clean --force \
    && groupmod --new-name pi node \
    && usermod --login pi --home /home/pi --move-home --shell /usr/sbin/nologin node

COPY --chmod=0555 bin/rr-pi-models.mjs /usr/local/bin/rr-pi-models

USER 1000:1000
WORKDIR /home/pi
